# Travis-CI for Drupal 8.

language: php
php:
  - 5.5

before_script:
  # Set up the Github OAuth token.
  # Please change this if you fork this project.
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json
  - composer selfupdate
  # Require drupal/core.
  - composer require drupal/core 8.0.*
  # Add PHPUnit, since require-dev of requirements aren't loaded.
  - composer require --dev phpunit/phpunit

script:
  # Our PHPUnit tests simply try to use classes which exist in Drupal core.
  - ./vendor/bin/phpunit
