# See composer.json for all the dependencies.

sudo: false

language: php

php:
  - 7.0

install:
  - composer install --no-progress --no-suggest

script:
  # Our tests try to access the container from \Drupal.
  - ./vendor/bin/phpunit
